### ISSUE TITLE
Setpgid, PTY & “operation not permitted”

### ISSUE THREAD

**Issue by keithpitt** [kr/pty#35] opened 2015-10-13 03:51 UTC
Here's a code snippet of running a bash script in a PTY:

`pty-test.go`

```go
package main

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path"
	"sync"
	"syscall"

	"github.com/kr/pty"
)

func main() {
	wd, _ := os.Getwd()
	c := exec.Command(path.Join(wd, "pty-test.sh"))
	c.Dir = wd
	c.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

	f, err := pty.Start(c)
	if err != nil {
		panic(err)
	}

	var wg sync.WaitGroup
	wg.Add(1)

	var buffer bytes.Buffer

	go func() {
		_, err = io.Copy(&buffer, f)
		if e, ok := err.(*os.PathError); ok && e.Err == syscall.EIO {
			// We can safely ignore this error, because it's just
			// the PTY telling us that it closed successfully. See:
			// https://github.com/buildkite/agent/pull/34#issuecomment-46080419
			err = nil
		}

		wg.Done()
	}()

	c.Wait()
	wg.Wait()

	fmt.Printf(buffer.String())
}
```

`pty-test.sh`

```golang
#!/bin/bash

echo "Oh hai there!"
```

If you build this program on OSX:

`GOOS=linux GOARCH=amd64 go build -o pty-test pty-test.go`

Then run it on Ubuntu, you get:

```
$ ./pty-test
Oh hai there!
```

If you build it directly on Ubuntu, or run it there via go run, you get:

```
$ go run pty-test.go
panic: fork/exec /root/pty-test.sh: operation not permitted

goroutine 1 [running]:
main.main()
	/root/pty-test.go:24 +0x229
exit status 2
```

If you remove the c.SysProcAttr = &syscall.SysProcAttr{Setpgid: true} line, it all works as expected...

Can anyone give me any pointers of what I may be doing wrong?

Thanks!

**Comment by keithpitt** [comment] 2015-10-13 06:15
This code was working before, but then I updated to the latest kr/pty https://github.com/kr/pty/commit/f7ee69f31298ecbe5d2b349c711e2547a617d398 with the fix for pre-existing settings on c.SysProcAttr. Looks like before my call to `Setpgid` was doing nothing.

**Comment by kr** [comment] 2015-10-14 05:36
Just to double-check, `/root/pty-test.sh` didn't somehow get marked as not-executable right?

What happens if you use `exec.Command("/bin/echo", "hello from echo")` instead?

**Comment by keithpitt** [comment] 2015-10-14 05:40
Yeah, I checked that as well (probably should have mentioned that in my bug report, sorry):

```go
func main() {
        c := exec.Command("ls")
        c.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}

        // ...
}
```

Returns:

```
panic: fork/exec /bin/ls: operation not permitted

goroutine 1 [running]:
main.main()
	/root/pty-test.go:22 +0x147
exit status 2
```

And with the `echo` example:

```
panic: fork/exec /bin/echo: operation not permitted

goroutine 1 [running]:
main.main()
	/root/pty-test.go:22 +0x18b
exit status 2
```

I did the test on a fresh Ubuntu instance that I setup on Digital Ocean (all I did was install latest Go) to make sure it wasn't something on my system doing something funny. I also tried running as a non-root user, and got the same behaviour.

**Comment by kr** [comment] 2015-10-14 06:08
Cool, I reproduced it.

Short answer, you can just remove the Setpgid flag. Because pty [sets the Setsid flag](https://github.com/kr/pty/blob/f7ee69f31298ecbe5d2b349c711e2547a617d398/run.go#L25) and according to the setsid man page on Ubuntu:

> setsid()  creates  a new session if the calling process is not a process group leader.  The calling process is the leader of the new session, the process group leader of the new process group, and has no controlling terminal.

I'm still not exactly sure why the error message comes up, but the man page for setpgid says:

> If setpgid() is used to move a process from one process group to another, … both process groups must be part of the same session (see setsid(2)) …

Browsing exec_linux.go in package syscall, we can see that it [calls setsid before setpgid](https://github.com/golang/go/blob/1d765b77a04fb12c2d97e0a8c9491de2bbfcbacc/src/syscall/exec_linux.go#L148-L163).

It seems to me that the setpgid call ought to succeed, but maybe setsid has something to do with it. Anyway, I think if you take out Setpgid you should be fine, because Setsid makes a new process group regardless.

**Comment by keithpitt** [comment] 2015-10-15 00:24
@kr great! Thanks so much for clarifying :+1: happy for you to close the issue now (unless you want to leave it open for further investigation)

**Comment by kr** [comment] 2015-10-15 05:02
Cool. I'm glad it worked out ok. :smiley:

**Closed by kr** 2015-10-15 05:02 UTC
