### ISSUE TITLE
 i got error at log.Printf("Failed to read from pty master: %s", err) "forum/#!forum/golang-nuts" Nobody helps me. I know you can.

### ISSUE THREAD

**Issue by Mountains-and-rivers** [kr/pty#77] opened 2019-04-01 16:51 UTC
# server.js
## code
```
'use strict'

let app = require('http').createServer(handler)
let io = require('socket.io')(app)

app.listen(3000)

console.log('Listening at http://localhost:3000/')

function handler (req, res) {
  res.writeHead(200)
  res.end('Testing server for http://github.com/wedeploy/gosocketio example.')
}
io.on('connection', function (socket) {
  console.log('Connecting %s.', socket.id)
  console.log(socket.request.headers)

  socket.on('messgae', (location) => {
    // fail booking 50% of the requests
    console.log('client message!')
    console.log(location)


    socket.send("t")
    socket.send("o")
    socket.send("p")
    socket.send("\n")
  })

  socket.on('result', (location) => {
    // fail booking 50% of the requests
    console.log('result message!')
    console.log(location)

  })


  socket.on('find_tickets', (route) => {
    console.log('Quote for tickets from %s to %s requested.', route.From, route.To)
  })

  socket.on('error', (err) => {
    console.error(err)
  })

  socket.on('disconnect', () => {
    console.log('Disconnecting %s.', socket.id)
  })
})
```
# client.go
## code
```
package main

import (
	"bytes"
	"encoding/gob"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"time"

	"github.com/Ali-IoT-Lab/socketio-client-go"
	"github.com/kr/pty"
)

type wsPty struct {
	Cmd *exec.Cmd // pty builds on os.exec
	Pty *os.File  // a pty is simply an os.File
}

func (wp *wsPty) Start() {
	var err error
	args := flag.Args()
	wp.Cmd = exec.Command(cmdFlag, args...)
	wp.Cmd.Env = append(os.Environ(), "TERM=xterm")
	wp.Pty, err = pty.Start(wp.Cmd)
	if err != nil {
		log.Fatalf("Failed to start command: %s\n", err)
	}
}

func (wp *wsPty) Stop() {
	wp.Pty.Close()
	wp.Cmd.Wait()
}

func GetBytes(key interface{}) ([]byte, error) {
	var buf bytes.Buffer
	enc := gob.NewEncoder(&buf)
	err := enc.Encode(key)
	if err != nil {
		return nil, err
	}
	return buf.Bytes(), nil

}

var cmdFlag string

func init() {
	flag.StringVar(&cmdFlag, "cmd", "/bin/bash", "command to execute on slave side of the pty")
	// TODO: make sure paths exist and have correct permissions
}
func main() {

	wp := wsPty{}
	// TODO: check for errors, return 500 on fail
	wp.Start()

	var Header http.Header = map[string][]string{
		"moja":     {"ccccc, asdasdasdasd"},
		"terminal": {"en-esadasdasdwrw"},
		"success":  {"dasdadas", "wdsadaderew"},
	}

	s, err := socketio.Socket("ws://127.0.0.1:3000")
	if err != nil {
		panic(err)
	}
	s.Connect(Header)
	s.Emit("messgae", "hello server!")

	s.On("message", func(args ...interface{}) {
		fmt.Println("-------------------11111-------------------------")
		//fmt.Printf("%T\n", args[0])
		res, _ := GetBytes(args[0])
		fmt.Println(string(res))
		wp.Pty.Write(res)
	})

	go func() {
		resBuf := make([]byte, 1024)
		for {
			fmt.Println("-----------------------2222222---------------------------")
			fmt.Println(string(resBuf))

			n, err := wp.Pty.Read(resBuf)
			if err != nil {
				log.Printf("Failed to read from pty master: %s", err)
				return
			}
			fmt.Println(n)
			// 	out := make([]byte, base64.StdEncoding.EncodedLen(n))
			// 	base64.StdEncoding.Encode(out, resBuf[0:n])

			// 	fmt.Println("-----------------------3333333---------------------------")
			// 	fmt.Println(string(resBuf[0:n]))

			// 	s.Emit("result", string(resBuf[0:n]))
		}

	}()

	time.Sleep(2 * time.Second)

	//wp.Stop()
	for {
		// s.Emit("messgae", "hello server!")
		// time.Sleep(2 * time.Second)
	}
}
```

**Comment by creack** [comment] 2019-04-01 16:53
When asking for help, please provide details on how to reproduce, details on what you are trying to achieve and details on what is the behavior you are seeing, as well as the steps taken to get there.
When providing a code sample, please clean it up and post only the relevant part.

**Comment by Mountains-and-rivers** [comment] 2019-04-01 17:02
> relevant
i send commond “top” by server，  ```
    socket.send("t")
    socket.send("o")
   socket.send("p")
    socket.send("\n")
```
client receive “top” command on “message” event
 ```

	s.On("message", func(args ...interface{}) {
		fmt.Println("-------------------11111-------------------------")
		//fmt.Printf("%T\n", args[0])
		res, _ := GetBytes(args[0])
		fmt.Println(string(res))
		wp.Pty.Write(res)
	})

```

and write "top\n" to tty 

```
	go func() {
		resBuf := make([]byte, 1024)
		for {
			fmt.Println("-----------------------2222222---------------------------")
			fmt.Println(string(resBuf))

			n, err := wp.Pty.Read(resBuf)
			if err != nil {
				log.Printf("Failed to read from pty master: %s", err)
				return
			}
			fmt.Println(n)
			// 	out := make([]byte, base64.StdEncoding.EncodedLen(n))
			// 	base64.StdEncoding.Encode(out, resBuf[0:n])

			// 	fmt.Println("-----------------------3333333---------------------------")
			// 	fmt.Println(string(resBuf[0:n]))

			// 	s.Emit("result", string(resBuf[0:n]))
		}

	}()

```

read result looply

but at ``` n, err := wp.Pty.Read(resBuf)``` return EOF , i learn golang 3 weeks ,i can find why?

**Comment by Mountains-and-rivers** [comment] 2019-04-01 17:08
I have to rest at 1 a.m.

**Comment by creack** [comment] 2019-04-01 17:23
There is obviously a language barrier.

As mentioned in previous conversation, `println` is incompatible with TTYs as it breaks the esacpe sequence with a `\n`. Commented code and lenghty debug print statements are irrelevants. You still didn't provide a way to reproduce, nor what is the expected result.

There is obviously a language barrier, but it feels like you are not putting any efforts  into it.

A few of thge problems with your request are (but not limited to):
- Poor message / title formatting, making it difficult to read
- Lack of clear expectation
- Lack of a way to reproduce
- Lack of steps / instructions
- Lot of irrelevant / ununsed code
- Includes Javascript / external libs in an issue on the PTY lib, this is not the place.
- Code includes bug already discussed in previous conversations (`println` is incompatible with tty).
- No context / explanation around the code itself: what is that "GetBytes" supposed to do? Why use "gob"? Why print the type of `args[0]`? Does the `println` in the `s.On("message"` indeed prints `"top\n"`?

Here is the sample code you provided, without the websocket, and it works as expected. The goal is to print `OK!` on the screen and wait forever while not getting an error reading the PTY.

```go
package main

import (
        "bytes"
        "encoding/gob"
        "flag"
        "log"
        "os"
        "os/exec"
        "time"

        "github.com/kr/pty"
)

type wsPty struct {
        Cmd *exec.Cmd // pty builds on os.exec
        Pty *os.File  // a pty is simply an os.File
}

func (wp *wsPty) Start() {
        var err error
        args := flag.Args()
        wp.Cmd = exec.Command(cmdFlag, args...)
        wp.Cmd.Env = append(os.Environ(), "TERM=xterm")
        wp.Pty, err = pty.Start(wp.Cmd)
        if err != nil {
                log.Fatalf("Failed to start command: %s\n", err)
        }
}

func (wp *wsPty) Stop() {
        wp.Pty.Close()
        wp.Cmd.Wait()
}

func GetBytes(key interface{}) ([]byte, error) {
        var buf bytes.Buffer
        enc := gob.NewEncoder(&buf)
        err := enc.Encode(key)
        if err != nil {
                return nil, err
        }
        return buf.Bytes(), nil

}

var cmdFlag string

func init() {
        flag.StringVar(&cmdFlag, "cmd", "/bin/bash", "command to execute on slave side of the pty")
}

func main() {
        wp := wsPty{}
        wp.Start()
        go func() {
                resBuf := make([]byte, 1024)
                for {
                        _, err := wp.Pty.Read(resBuf)
                        if err != nil {
                                log.Printf("Failed to read from pty master: %s", err)
                                return
                        }
                }
        }()

        go func() {
                wp.Pty.Write([]byte("t"))
                wp.Pty.Write([]byte("o"))
                wp.Pty.Write([]byte("p"))
                wp.Pty.Write([]byte("\n"))
                println("OK!")
        }()

        time.Sleep(2 * time.Second)

        for {
        }
}
```

Closing as it is the wrong place. If the golang mailing list didn't help, please try stackoverflow, or try the github for the websocket as the issue seems to be there.

**Closed by creack** 2019-04-01 17:23 UTC
